"""Ordinary F-backed Session input projection; no invocation or execution state."""
import base64
import copy
import json
import os
from pathlib import Path
from lore_execution.errors import require
from lore_execution.journal import canonical, digest, sync_dir
from lore_execution.ordinary_sources import document, file_object, reference
from lore_files.archive import materialize_tree
from lore_files.metadata import walk
from lore_files.util import identity


def immutable(path, data):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    require(not path.is_symlink(), "INVALID_REQUEST", "generated original is symlink")
    if path.exists():
        require(file_object(path, max(len(data), 1))[1] == data,
                "INVALID_REQUEST", "original generated bytes changed")
    else:
        with path.open("xb") as out:
            out.write(data); out.flush(); os.fsync(out.fileno())
        sync_dir(path.parent)
    return file_object(path, max(len(data), 1))[0]


def json_file(path, value):
    return immutable(path, canonical(value) + b"\n")


def compact(full):
    encoded = json.dumps(full, sort_keys=True, separators=(",", ":"), ensure_ascii=True, allow_nan=False).encode()
    return dict(id=digest(encoded), sha256=full["sha256"])


def history_catalog(version):
    require(type(version) is dict and set(version) == {'resource_id', 'domain', 'profile',
            'git_ref', 'archive_sha256', 'manifest_sha256'} and version['domain'] == 'workspace' and
            version['profile'] == 'host-v1', 'INVALID_REQUEST', 'complete Workspace history version required')
    return [dict(version_ref=copy.deepcopy(version), read_path='/input/history/' + digest(canonical(version)))]


class InputFiles:
    def __init__(self, files, host, register):
        self.files, self.host, self.register = files, host, register
        self.root = Path(host["plan_root"])
        require(self.root.is_absolute() and self.root.resolve() == self.root,
                "UNAUTHORIZED", "owned generated-input root required")
        self.root.mkdir(mode=0o700, parents=True, exist_ok=True)

    def checked_view(self, view, version=None, registration=None):
        bundle, material = view["bundle"], view["materialized"]
        version = version or bundle["version_ref"]
        require(bundle["version_ref"] == material["version_ref"] == version,
                "INVALID_REQUEST", "F complete version/materialization differs")
        self.files.versions.validate_bundle(bundle)
        path = Path(material["path"])
        require(path.is_absolute() and path.resolve() == path and identity(path) == material["root"],
                "INVALID_REQUEST", "F materialized root replaced")
        if registration is not None:
            require(str(path) == registration["path"] and material["root"] ==
                    {k: registration[k] for k in ("dev", "ino")},
                    "UNAUTHORIZED", "F view is not original R registered root")
        _, tree, contents = self.files.versions.load(version)
        require(walk(path, self.files.limits)[0] == tree,
                "INVALID_REQUEST", "F materialized complete tree changed")
        return path, tree, contents

    def capture(self, directory, name, invocation, provenance):
        source = directory / (name + "-source")
        binding = dict(resource_id="session-input-" + digest(str(source).encode()),
                       domain="surface", path=str(source), root=identity(source), revision=1,
                       authorization=self.host["authorization"])
        coordination = dict(owner="trusted-session-plans", invocation_id=invocation,
                            original_sources=provenance)
        request_id = "session-plan-" + digest(str(source).encode())
        bundle = self.files.capture(request_id, binding, coordination)
        material = self.files.materialize(request_id + "-read", bundle["version_ref"],
                                         str(directory / (name + "-read")), self.host["authorization"])
        return dict(bundle=bundle, materialized=material)

    def descriptor(self, directory, invocation, body):
        source = directory / "descriptor-source"; source.mkdir(exist_ok=True)
        data = canonical(body) + b"\n"
        immutable(source / "input.json", data)
        view = self.capture(directory, "descriptor", invocation, body)
        full = dict(owner="F", kind="file", path="input.json",
                    version_ref=view["bundle"]["version_ref"], sha256=digest(data))
        require(self.files.read_reference(full, self.host["authorization"]) == data,
                "INVALID_REQUEST", "F descriptor content differs")
        return full

    def input(self, directory, invocation, surface, e_files, originals, feedback, config, provenance, *, history_view):
        source = directory / "input-source"
        _, tree, contents = self.checked_view(surface)
        catalog = history_catalog(history_view['bundle']['version_ref'])
        _, history_tree, history_contents = self.checked_view(history_view)
        require(config['input'].get('history_views') == catalog,
                'INVALID_REQUEST', 'history catalog differs from original accepted Workspace')
        if not source.exists():
            source.mkdir()
            materialize_tree(tree, contents, source / "surface", self.files.limits)
        else:
            require(walk(source / "surface", self.files.limits)[0] == tree,
                    "INVALID_REQUEST", "original projected Surface changed")
        history_root = source / 'history'
        require(not history_root.is_symlink() and history_root.resolve() == history_root,
                'INVALID_REQUEST', 'history root alias rejected')
        history_root.mkdir(exist_ok=True)
        name = catalog[0]['read_path'].rsplit('/', 1)[1]
        target = history_root / name
        if target.exists():
            require(not target.is_symlink() and walk(target, self.files.limits)[0] == history_tree,
                    'INVALID_REQUEST', 'original projected history changed')
        else:
            materialize_tree(history_tree, history_contents, target, self.files.limits)
        require({p.name for p in history_root.iterdir()} == {name},
                'INVALID_REQUEST', 'unexpected historical input version')
        for name, data in e_files.items(): immutable(source / name, data)
        immutable(source / "feedback.txt", feedback)
        for name, row in originals.items(): immutable(source / "originals" / name, row["raw"])
        json_file(source / "node-config.json", config)
        wanted = {"surface", "history", "feedback.txt", "node-config.json", *e_files}
        if originals: wanted.add("originals")
        require({p.name for p in source.iterdir()} == wanted,
                "INVALID_REQUEST", "unexpected input projection member")
        return self.capture(directory, "input", invocation, provenance)

    def mount(self, view, role, directory):
        root, tree, _ = self.checked_view(view)
        source = dict(path=str(root), **identity(root))
        original = file_object(view["bundle"]["manifest_path"])[0]
        content = dict(owner="F", version_ref=view["bundle"]["version_ref"],
                       original_manifest=original, materialized_root=source)
        entries = {}
        for name, saved in tree["entries"].items():
            require(not saved["xattrs"], "INVALID_REQUEST", "Node readonly profile does not support xattrs")
            row = {k: saved[k] for k in ("kind", "mode", "uid", "gid", "mtime_ns")}
            if row["kind"] == "file": row.update(byte_length=saved["size"], sha256=saved["sha256"])
            if row["kind"] == "symlink":
                link = os.fsdecode(base64.b64decode(saved["target_b64"]))
                actual = (root / name).resolve(strict=True)
                require(actual.is_relative_to(root), "INVALID_REQUEST", "readonly symlink escapes source")
                row.update(target=link, resolved_relative=actual.relative_to(root).as_posix())
            entries[name] = row
        manifest = dict(schema="lore-x-readonly-tree/v1", role=role, root=source,
                        entries=entries, source_ref=content)
        mount = dict(role=role, source=source, target="/" + role, read_only=True,
                     manifest_ref=json_file(directory / (role + "-readonly.json"), manifest), content_ref=content)
        self.register("readonly-view", mount, dict(namespace=self.host["namespace"], role=role))
        return mount
