#!/usr/bin/env python3
"""Build an offline, expandable cloc report for a Git working directory."""
import argparse
from collections import Counter
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import tempfile


SOURCE = set('.go .py .js .mjs .cjs .ts .tsx .jsx .sh .bash .zsh .c .h .cc .cpp .hpp .rs .java .kt .swift .rb .php .sql .html .css .scss .vue .svelte .proto .lua .pl .ex .exs .lean'.split())
DEPENDENCIES = {'node_modules', 'vendor', '.venv', '.venvs', 'build', 'dist', '__pycache__'}
TOOL_FILES = {'scripts/code_size.py', 'scripts/code_size.html'}
LABELS = {'implementation': '实现', 'test': '测试', 'tooling': '分析工具', 'generated': '生成代码'}


def command(args, cwd):
    return subprocess.check_output(args, cwd=cwd)


def category(path, data):
    if re.search(rb'(?im)^\s*(?://|#|/\*|\*)\s*(?:Code generated\b.*DO NOT EDIT|@generated\b|Generated by\b)', data[:4096]):
        return 'generated'
    if 'tests' in path.parts or 'test' in path.parts or path.name.startswith('test_') or path.stem.endswith(('_test', '.test', '.spec')):
        return 'test'
    return 'tooling' if path.as_posix() in TOOL_FILES else 'implementation'


def collect(root):
    root = root.resolve()
    inventory = command(['git', 'ls-files', '-z', '--cached', '--others', '--exclude-standard', '--', '.'], root)
    files, excluded = [], []
    with tempfile.TemporaryDirectory(prefix='loom-code-size-') as tmp:
        snapshot = Path(tmp)
        metadata = {}
        for name in sorted(set(inventory.decode().split('\0')) - {''}):
            path, source = Path(name), root / name
            reason = None
            if source.is_symlink() or any(p.is_symlink() for p in source.parents if p != root):
                reason = '符号链接'
            elif not source.is_file():
                reason = '已删除或非普通文件（含子模块）'
            elif DEPENDENCIES.intersection(path.parts):
                reason = '依赖或构建目录'
            elif path.parts[0] in {'docs', 'templates'}:
                reason = '文档或模板'
            elif path.suffix.lower() not in SOURCE and path.name not in {'Dockerfile', 'Makefile'}:
                reason = '非代码文件（配置、依赖锁、文档等）'
            if reason:
                excluded.append({'path': name, 'reason': reason})
                continue
            if '\n' in name or '\r' in name:
                raise ValueError(f'cloc 文件列表不支持换行文件名：{name!r}')
            data = source.read_bytes()
            target = snapshot / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
            metadata[name] = {'category': category(path, data), 'sha256': hashlib.sha256(data).hexdigest()}
        listing = snapshot / '_cloc-files.txt'
        listing.write_text(''.join('./' + name + '\n' for name in metadata), encoding='utf-8')
        raw = command(['cloc', '--json', '--by-file', '--quiet', '--skip-uniqueness',
                       '--timeout=0', f'--list-file={listing}'], snapshot) if metadata else b'{}'
        counts = json.loads(raw)
        for name, row in counts.items():
            if name in {'header', 'SUM'}:
                continue
            name = Path(name).as_posix()
            files.append({'path': name, **row, **metadata.pop(name)})
        # Never publish a partial count as if all selected source was measured.
        for name, row in metadata.items():
            if (snapshot / name).stat().st_size:
                raise ValueError(f'cloc 未统计选中的非空代码文件：{name}')
            files.append({'path': name, 'code': 0, 'blank': 0, 'comment': 0, 'language': 'Empty', **row})
    return sorted(files, key=lambda row: (-row['code'], row['path'])), excluded


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('directory', nargs='?', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--output', type=Path, help='Output directory (default: DIRECTORY/.local/code-size)')
    parser.add_argument('--threshold', type=int, default=10000, help='Implementation review threshold, not a build gate')
    args = parser.parse_args()
    if args.threshold <= 0:
        parser.error('--threshold must be positive')
    if not shutil.which('cloc'):
        parser.error('Install cloc first: brew install cloc (macOS), apt install cloc (Debian/Ubuntu)')
    root = args.directory.resolve()
    output = (args.output or root / '.local/code-size').resolve()
    version = command(['cloc', '--version'], root).decode().strip()
    files, excluded = collect(root)
    totals = {key: {'files': 0, 'code': 0, 'comment': 0, 'blank': 0} for key in LABELS}
    for row in files:
        total = totals[row['category']]
        total['files'] += 1
        for key in ('code', 'comment', 'blank'):
            total[key] += row[key]
    report = {'created_at': datetime.now(timezone.utc).isoformat(), 'root': str(root),
              'cloc_version': version, 'threshold': args.threshold,
              'files': files, 'excluded': excluded, 'totals': totals}
    payload = json.dumps(report, ensure_ascii=False, indent=2)
    template = Path(__file__).with_suffix('.html').read_text(encoding='utf-8')
    output.mkdir(parents=True, exist_ok=True)
    (output / 'report.json').write_text(payload + '\n', encoding='utf-8')
    # Inline only counts and paths, never source; escape HTML script terminators.
    (output / 'index.html').write_text(template.replace('/*REPORT_DATA*/', payload.replace('<', '\\u003c')), encoding='utf-8')
    for key, label in LABELS.items():
        print(f"{label}: {totals[key]['code']:,} 代码行 / {totals[key]['files']} 文件")
    actual = totals['implementation']['code']
    print(f"实现 / {args.threshold:,} 行反思阈值: {actual / args.threshold:.2f}×")
    modules = Counter()
    for row in files:
        if row['category'] == 'implementation':
            modules[str(Path(row['path']).parent)] += row['code']
    for path, count in modules.most_common(10):
        print(f'  {count:>7,}  {path}')
    print(f'报告: {output / "index.html"}')


if __name__ == '__main__':
    main()
